"use strict";
(function(){
if(window.__algoTreeMasteryLoaded)return;window.__algoTreeMasteryLoaded=true;
var wrap=document.querySelector('main .wrap'), side=document.getElementById('side');
if(!wrap||!side)return;

var st=document.createElement('style');
st.textContent=`
/* ===== TREE MASTERY ===== */
.tm-hero{margin-bottom:18px}.tm-kicker{font:800 10px var(--mono);letter-spacing:1.35px;text-transform:uppercase;color:var(--gr);margin-bottom:7px}
.tm-tabs,.tm-topics{display:flex;gap:7px;flex-wrap:wrap;margin:13px 0}.tm-tab,.tm-topic{border:1px solid var(--line2);background:var(--panel);color:var(--dim);border-radius:7px;padding:7px 10px;font:700 10px var(--mono);cursor:pointer}.tm-tab.on,.tm-topic.on{border-color:var(--gr);color:var(--gr);background:color-mix(in srgb,var(--gr) 8%,var(--panel))}
.tm-pane{display:none}.tm-pane.on{display:block}.tm-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(285px,1fr));gap:11px}.tm-card{background:var(--panel);border:1px solid var(--line);border-radius:11px;padding:15px 16px;margin-top:11px}.tm-grid>.tm-card{margin-top:0}.tm-card h3{margin:0 0 7px}.tm-badge{display:inline-block;font:800 9px var(--mono);letter-spacing:.9px;text-transform:uppercase;color:var(--gr);margin-bottom:6px}.tm-rule{font:700 13px/1.55 var(--mono);background:var(--panel2);border:1px solid var(--line);border-radius:7px;padding:9px 10px;margin:9px 0;color:var(--ink)}.tm-note{margin-top:9px;border-left:3px solid var(--am);background:color-mix(in srgb,var(--am) 6%,var(--panel2));padding:8px 10px;border-radius:0 7px 7px 0;color:var(--dim)}.tm-good{border-left-color:var(--gr);background:color-mix(in srgb,var(--gr) 6%,var(--panel2))}.tm-small{font-size:13px;color:var(--dim)}
.tm-table{width:100%;border-collapse:collapse;margin-top:9px;font-size:13.5px}.tm-table th,.tm-table td{text-align:left;vertical-align:top;padding:8px 9px;border-bottom:1px solid var(--line)}.tm-table th{font:800 9px var(--mono);letter-spacing:.8px;color:var(--faint);text-transform:uppercase}.tm-table tr:last-child td{border-bottom:0}
.tm-labgrid{display:grid;grid-template-columns:minmax(280px,.8fr) minmax(320px,1.2fr);gap:12px}.tm-inputrow{display:flex;gap:7px;flex-wrap:wrap;margin-top:9px}.tm-input{flex:1;min-width:190px;border:1px solid var(--line2);background:var(--panel2);color:var(--ink);border-radius:7px;padding:8px 10px;font:12px var(--mono);outline:0}.tm-input:focus{border-color:var(--gr)}.tm-btn{border:1px solid var(--line2);background:var(--panel2);color:var(--ink);border-radius:7px;padding:8px 10px;font:700 10px var(--mono);cursor:pointer}.tm-btn:hover{border-color:var(--gr);color:var(--gr)}.tm-btn.primary{border-color:var(--gr);color:var(--gr)}
#tmTreeCanvas{min-height:290px;display:flex;align-items:center;justify-content:center;overflow:auto;background:var(--panel2);border:1px solid var(--line);border-radius:10px;padding:12px}.tm-svg line{stroke:var(--tline);stroke-width:1.7}.tm-svg circle{fill:var(--panel);stroke:var(--gr);stroke-width:1.8}.tm-svg text{fill:var(--ink);font:700 12px var(--mono);text-anchor:middle;dominant-baseline:middle}.tm-path circle{stroke:var(--am);fill:color-mix(in srgb,var(--am) 12%,var(--panel))}
.tm-outs{display:grid;gap:7px;margin-top:9px}.tm-out{background:var(--panel2);border:1px solid var(--line);border-radius:7px;padding:8px 10px}.tm-out b{display:block;font:800 9px var(--mono);letter-spacing:.8px;color:var(--faint);text-transform:uppercase;margin-bottom:2px}.tm-out code{color:var(--gr)}
.tm-qcard{background:var(--panel);border:1px solid var(--line);border-radius:11px;padding:16px;margin-top:11px}.tm-qmeta{font:800 9px var(--mono);letter-spacing:1px;color:var(--gr);text-transform:uppercase}.tm-qtext{font-size:17px;font-weight:700;line-height:1.45;margin:7px 0 11px}.tm-opt{display:block;width:100%;text-align:left;border:1px solid var(--line);background:var(--panel2);color:var(--ink);border-radius:8px;padding:10px 12px;margin-top:7px;cursor:pointer}.tm-opt:hover:not(:disabled){border-color:var(--gr)}.tm-opt.right{border-color:var(--gr);color:var(--gr);background:color-mix(in srgb,var(--gr) 9%,var(--panel))}.tm-opt.wrong{border-color:var(--rd);color:var(--rd);background:color-mix(in srgb,var(--rd) 8%,var(--panel))}.tm-explain{display:none;margin-top:11px;border-left:3px solid var(--gr);background:var(--panel2);padding:10px 12px;border-radius:0 7px 7px 0}.tm-explain.on{display:block}.tm-qnav{display:flex;justify-content:space-between;gap:7px;margin-top:11px;flex-wrap:wrap}
.tm-rot{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:10px}.tm-rot button{border:1px solid var(--line2);background:var(--panel2);color:var(--ink);border-radius:8px;padding:11px 7px;font:800 11px var(--mono);cursor:pointer}.tm-rot button:hover{border-color:var(--am)}.tm-result{margin-top:9px;font-size:13px;min-height:24px}.tm-result.good{color:var(--gr)}.tm-result.bad{color:var(--rd)}
.tm-check{display:grid;grid-template-columns:repeat(auto-fit,minmax(255px,1fr));gap:9px}.tm-skill{display:flex;gap:10px;align-items:flex-start;background:var(--panel);border:1px solid var(--line);border-radius:9px;padding:11px 12px}.tm-skill input{margin-top:4px;accent-color:var(--gr)}.tm-skill b{display:block}.tm-skill span{display:block;color:var(--dim);font-size:12.5px;margin-top:2px}.tm-progress{margin:12px 0;height:9px;background:var(--panel2);border:1px solid var(--line);border-radius:999px;overflow:hidden}.tm-progress>i{display:block;height:100%;width:0;background:var(--gr);transition:.2s}.tm-scoreline{font:800 11px var(--mono);color:var(--gr)}
@media(max-width:760px){.tm-labgrid{grid-template-columns:1fr}.tm-rot{grid-template-columns:1fr 1fr}}
`;
document.head.appendChild(st);

var codeBtn=side.querySelector('[data-page="practice"]');
var nav=document.createElement('button');nav.className='navbtn';nav.dataset.page='trees';nav.setAttribute('onclick',"go('trees')");nav.innerHTML='<span class="dot" style="background:var(--gr)"></span>Tree mastery<span class="num">W4+6</span>';
if(codeBtn&&codeBtn.nextSibling)side.insertBefore(nav,codeBtn.nextSibling);else side.appendChild(nav);

var topics={
 basics:{name:'Tree basics',week:'W4',exam:'Root, leaf, path, level, height, complete binary tree.',html:`<div class="tm-grid"><div class="tm-card"><span class="tm-badge">FOUNDATION</span><h3>Tree vocabulary</h3><table class="tm-table"><tr><td><b>Root</b></td><td>Only node with no parent.</td></tr><tr><td><b>Leaf</b></td><td>Node with no children.</td></tr><tr><td><b>Path length</b></td><td>Number of arcs on the path.</td></tr><tr><td><b>Level</b></td><td>Path length + 1. Root is level 1.</td></tr><tr><td><b>Height</b></td><td>Longest path length, counted in arcs. One-node tree has height 0.</td></tr></table></div><div class="tm-card"><span class="tm-badge">BINARY TREE</span><h3>Binary vs complete</h3><p>A binary tree gives each node at most two children. The course's complete-tree fact is:</p><div class="tm-rule">m = k + 1</div><p class="tm-small">m = leaves, k = nonterminal nodes, when every nonterminal node has exactly two nonempty children.</p><div class="tm-note"><b>Exam trap:</b> height counts arcs, not nodes.</div></div></div>`},
 bst:{name:'BST',week:'W4',exam:'Rule, search, insertion, deletion, complexity, IPL.',html:`<div class="tm-grid"><div class="tm-card"><span class="tm-badge">CORE RULE</span><h3>Binary Search Tree</h3><div class="tm-rule">left subtree &lt; node &lt; right subtree</div><p>Search: equal → found; smaller → left; larger → right; NULL → not present.</p><p><b>Worst search:</b> O(n) when shaped like a list. <b>Balanced:</b> about O(log n). Course average idea: IPL ÷ n.</p></div><div class="tm-card"><span class="tm-badge">INSERT / DELETE</span><h3>Insertion and 3 deletion cases</h3><ol><li>Leaf → remove it.</li><li>One child → parent adopts the child.</li><li>Two children → use merging or copying.</li></ol><div class="tm-note tm-good"><b>Copying:</b> copy predecessor (rightmost of left) or successor (leftmost of right), then delete that easier node.</div></div><div class="tm-card"><span class="tm-badge">MERGING</span><h3>Deletion by merging</h3><p>Root of left subtree replaces deleted node. Rightmost node of that left subtree adopts the original right subtree.</p><div class="tm-note">Can increase/decrease height and may make the tree less balanced.</div></div></div>`},
 traversal:{name:'Traversal',week:'W4',exam:'BFS; VLR, LVR, LRV; iterative; threaded; Morris.',html:`<div class="tm-grid"><div class="tm-card"><span class="tm-badge">DEPTH FIRST</span><h3>The letters are the definition</h3><table class="tm-table"><tr><td><b>VLR</b></td><td>Pre-order</td><td>Visit first</td></tr><tr><td><b>LVR</b></td><td>In-order</td><td>Visit between</td></tr><tr><td><b>LRV</b></td><td>Post-order</td><td>Visit last</td></tr></table><div class="tm-note tm-good"><b>BST special:</b> LVR gives sorted order.</div></div><div class="tm-card"><span class="tm-badge">BREADTH FIRST</span><h3>Level by level</h3><p>Implemented with a <b>queue</b>: enqueue root → dequeue/visit → enqueue children → repeat.</p><div class="tm-note">Iterative pre-order uses a stack. Push right before left so left is popped first.</div></div><div class="tm-card"><span class="tm-badge">NO RECURSION</span><h3>Threaded trees & Morris</h3><p><b>Threaded:</b> extra links point to predecessor/successor in traversal order.</p><p><b>Morris:</b> temporarily reshapes links so traversal uses O(1) extra space, then restores the tree.</p><div class="tm-note">Course emphasis: the main win is <b>space</b>, not asymptotic time; traversal is still O(n).</div></div></div>`},
 dsw:{name:'DSW balancing',week:'W4',exam:'Whole-tree balancing by rotations; backbone then compress.',html:`<div class="tm-grid"><div class="tm-card"><span class="tm-badge">DAY–STOUT–WARREN</span><h3>Two phases</h3><ol><li><b>Stretch:</b> rotate away left children until the tree is a right-leaning backbone.</li><li><b>Balance:</b> rotate every other node around its parent; repeat compressions until balanced.</li></ol><div class="tm-rule">Whole-tree rebalance: O(n)</div></div><div class="tm-card"><span class="tm-badge">WHEN</span><h3>DSW vs AVL</h3><p>DSW is useful when many changes happen and you rebalance only occasionally. AVL maintains local balance after each insertion/deletion.</p><div class="tm-note"><b>Rotation rule:</b> the middle subtree switches parents.</div></div></div>`},
 avl:{name:'AVL',week:'W4',exam:'Balance factor; LL/RR/LR/RL; lowest unbalanced node.',html:`<div class="tm-grid"><div class="tm-card"><span class="tm-badge">BALANCE</span><h3>AVL invariant</h3><div class="tm-rule">BF = height(left) − height(right) ∈ {−1, 0, +1}</div><p>Empty subtree height = −1. When a node reaches +2 or −2, rebalance at the <b>lowest</b> unbalanced node.</p></div><div class="tm-card"><span class="tm-badge">ROTATIONS</span><h3>Four cases</h3><table class="tm-table"><tr><td><b>LL</b></td><td>single right rotation</td></tr><tr><td><b>RR</b></td><td>single left rotation</td></tr><tr><td><b>LR</b></td><td>left at child, then right at parent</td></tr><tr><td><b>RL</b></td><td>right at child, then left at parent</td></tr></table><div class="tm-note">Classify the case by where the inserted key landed relative to the unbalanced node.</div></div></div>`},
 splay:{name:'Splay',week:'W4',exam:'Self-adjusting BST; 3 splay cases; amortized O(log n).',html:`<div class="tm-grid"><div class="tm-card"><span class="tm-badge">SELF-ADJUSTING</span><h3>Splay tree</h3><p>Every access reorganizes the BST so recently used elements move toward the root. Search, insert and delete are <b>O(log n) amortized</b>.</p></div><div class="tm-card"><span class="tm-badge">3 CASES</span><h3>Splaying</h3><ol><li>Parent is root → one rotation.</li><li><b>Homogeneous</b> (left-left or right-right) → parent around grandparent first, then node around parent.</li><li><b>Heterogeneous</b> (left-right or right-left) → node around parent first, then around grandparent.</li></ol><div class="tm-note">Course verdict: experimentally AVL often wins despite splay's amortized guarantee.</div></div></div>`},
 heap:{name:'Heap & heapsort',week:'W4',exam:'Heap property, priority queue operations, heapsort.',html:`<div class="tm-grid"><div class="tm-card"><span class="tm-badge">MAX HEAP</span><h3>Heap rule</h3><p>Every parent ≥ its children; tree is complete with last-level leaves packed left. Min heap reverses the comparison.</p><div class="tm-note"><b>Not a BST:</b> left and right siblings have no ordering relationship.</div></div><div class="tm-card"><span class="tm-badge">PRIORITY QUEUE</span><h3>Enqueue / dequeue</h3><p><b>Enqueue:</b> add at bottom, climb up while heap property is broken.</p><p><b>Dequeue:</b> remove root, move last node to root, sink it down with the larger child.</p></div><div class="tm-card"><span class="tm-badge">HEAPSORT</span><h3>Sort in place</h3><ol><li>Build heap.</li><li>Swap root/max with final unsorted position.</li><li>Reduce heap size and re-heap.</li><li>Repeat.</li></ol><div class="tm-rule">Heapsort: O(n log n)</div></div></div>`},
 expr:{name:'Expression tree',week:'W4',exam:'Operators/operands and infix/prefix/postfix via traversals.',html:`<div class="tm-grid"><div class="tm-card"><span class="tm-badge">EXPRESSION TREE</span><h3>Structure</h3><p>Operators are internal nodes; operands are leaves. The tree removes ambiguity about grouping.</p></div><div class="tm-card"><span class="tm-badge">NOTATION</span><h3>Traversal gives notation</h3><table class="tm-table"><tr><td><b>LVR</b></td><td>Infix</td></tr><tr><td><b>VLR</b></td><td>Polish / prefix</td></tr><tr><td><b>LRV</b></td><td>Reverse Polish / postfix</td></tr></table><div class="tm-note">Prefix and postfix do not need parentheses because the tree structure fixes the order.</div></div></div>`},
 btree:{name:'B-Tree family',week:'W6',exam:'Multiway, B, B*, B**, B+, Prefix B+, Bit Tree.',html:`<div class="tm-grid"><div class="tm-card"><span class="tm-badge">WHY</span><h3>Disk changes the design goal</h3><p>Seek time is mechanical and expensive. One B-tree node matches a disk block so each seek returns many keys.</p><div class="tm-note tm-good">Do more cheap CPU work if it removes a disk seek.</div></div><div class="tm-card"><span class="tm-badge">MULTIWAY / B</span><h3>Core rules</h3><p>A node with <b>k keys has k+1 pointers</b>. B-tree order m means at most m pointers and m−1 keys.</p><p>All leaves are on the same level; non-root nodes are at least half full.</p><div class="tm-note"><b>Order 5:</b> max 5 pointers, max 4 keys; overflow on the 5th key.</div></div><div class="tm-card"><span class="tm-badge">INSERT</span><h3>Split and promote</h3><ol><li>Insert into target leaf.</li><li>If overflow: split around median.</li><li>Median moves up to parent.</li><li>Repeat upward if parent overflows.</li></ol><div class="tm-note">Tree height grows only when the <b>root</b> splits.</div></div><div class="tm-card"><span class="tm-badge">VARIANTS</span><h3>B*, B**, B+</h3><table class="tm-table"><tr><td><b>B</b></td><td>≥ 1/2 full</td></tr><tr><td><b>B*</b></td><td>≥ 2/3 full; overflow to sibling; 2 nodes → 3</td></tr><tr><td><b>B**</b></td><td>≥ 3/4 full</td></tr><tr><td><b>B+</b></td><td>All data in leaves; internal keys are indexes; leaves linked</td></tr></table></div><div class="tm-card"><span class="tm-badge">SMALLER INDEX</span><h3>Prefix B+ and Bit Tree</h3><p><b>Prefix B+:</b> store only enough prefix to separate child ranges.</p><p><b>Bit Tree:</b> store the distinction bit — first bit position where values differ.</p><div class="tm-note">Smaller index keys → more keys per node → more children → fewer levels/seeks.</div></div></div>`},
 trie:{name:'Trie',week:'W6',exam:'Navigate using pieces of the key itself.',html:`<div class="tm-grid"><div class="tm-card"><span class="tm-badge">RETRIEVAL</span><h3>Trie</h3><p>A trie navigates by consuming the key one part at a time. A character or bit chooses the next branch; the root-to-node path spells the key.</p><div class="tm-note tm-good">Unlike a BST, you do not compare the whole key at each node.</div></div><div class="tm-card"><span class="tm-badge">WHY</span><h3>When it helps</h3><p>Useful when prefixes matter and when navigating by partial keys is cheaper than repeatedly comparing full keys.</p><p class="tm-small">The course introduces tries after Prefix B+ / Bit Trees because all three exploit only the distinguishing parts of a key.</p></div></div>`}
};

var skills=[
['basics','I can identify root, leaf, path, level and height correctly.'],['bst','I can build/search a BST from an insertion sequence.'],['bst','I can delete leaf, one-child and two-child BST nodes.'],['traversal','I can produce VLR, LVR, LRV and breadth-first orders.'],['traversal','I can explain stack/queue/threaded/Morris traversal choices.'],['dsw','I can explain both DSW phases and why it is O(n).'],['avl','I can calculate AVL balance factors.'],['avl','I can identify LL/RR/LR/RL and choose the correct rotation(s).'],['splay','I can identify the three splay cases.'],['heap','I can insert/remove in a heap and explain heapsort.'],['expr','I can convert expression-tree traversals to infix/prefix/postfix.'],['btree','I can use order m to find max keys/pointers in a B-tree node.'],['btree','I can perform/describe a B-tree split and median promotion.'],['btree','I can distinguish B, B*, B**, B+, Prefix B+ and Bit Trees.'],['trie','I can explain how a trie searches by key parts.']
];

var QB=[
['basics','A single-node tree has what height in this course?',['0','1','−1','2'],0,'Height counts arcs. A single node has no arcs below it, so height = 0.'],
['basics','A node at path length 3 is on which level?',['2','3','4','5'],2,'Level = path length + 1, so 3 + 1 = 4.'],
['basics','If every nonterminal node has exactly two nonempty children and k=7 internal nodes, how many leaves m?',['6','7','8','14'],2,'Course fact: m = k + 1, so 8 leaves.'],
['bst','Which rule defines a BST?',['parent ≥ children','left < node < right','all leaves same level','left and right have equal height'],1,'BST ordering is left subtree < node < right subtree.'],
['bst','A balanced BST with 10,000 nodes needs about how many tests in the course example?',['14','100','1000','10000'],0,'The course uses lg(10,001) ≈ 13.3, rounded to about 14 tests.'],
['bst','Deleting a BST node with two children by copying usually copies…',['any leaf','the root','predecessor or successor','the parent'],2,'Copy the predecessor (rightmost of left subtree) or successor (leftmost of right), then delete that easier node.'],
['bst','Deletion by merging makes which node replace the deleted node?',['root of left subtree','root of right subtree only','parent','smallest leaf'],0,'Course merging rule: left-subtree root replaces it; rightmost node of that left subtree adopts the original right subtree.'],
['traversal','Which traversal gives sorted order on a BST?',['VLR','LVR','LRV','BFS'],1,'In-order LVR visits smaller values, then node, then larger values.'],
['traversal','Breadth-first traversal uses which structure?',['stack','queue','heap','trie'],1,'Enqueue root, then dequeue/visit and enqueue children.'],
['traversal','Iterative pre-order pushes right child before left because…',['right must be visited first','stack is FIFO','left should pop first','it balances the tree'],2,'A stack is LIFO. Push right first so left is on top and is processed first.'],
['traversal','What is the main advantage of Morris traversal?',['O(log n) time','sorted output only','O(1) extra space','works only on heaps'],2,'The course emphasizes space saving. Morris temporarily rewires the tree and restores it; traversal time remains O(n).'],
['dsw','What is DSW phase 1?',['sort into array','stretch tree into a right backbone','heapify','split full nodes'],1,'DSW first removes left children by rotations until the tree becomes a right-leaning backbone.'],
['dsw','DSW rebalances the whole tree in…',['O(1)','O(log n)','O(n)','O(n²)'],2,'The course gives DSW whole-tree balancing as O(n).'],
['avl','AVL balance factor on the slides is…',['right−left','left−right','left+right','node count difference'],1,'BF = height(left) − height(right).'],
['avl','A key lands in the left subtree of the left child and BF becomes +2. Which case/fix?',['LL → right rotation','RR → left rotation','LR → double rotation','RL → double rotation'],0,'Left-left imbalance is fixed by one right rotation.'],
['avl','A key lands right of the left child. Which AVL case?',['LL','RR','LR','RL'],2,'From the unbalanced node: first left, then right = LR. It needs a double rotation.'],
['avl','Where should you rebalance after an AVL insertion?',['always at root','highest unbalanced node','lowest node that reaches ±2','new leaf'],2,'Fix the lowest unbalanced ancestor first.'],
['splay','In a homogeneous splay case, which rotation happens first?',['node around parent','parent around grandparent','root around node','no rotation'],1,'Homogeneous means zig-zig: rotate parent around grandparent first, then node around parent.'],
['splay','Splay operations are guaranteed…',['O(1) worst-case','O(log n) amortized','O(log n) worst-case per operation','O(n²) amortized'],1,'Individual operations can be expensive, but over a sequence the amortized bound is O(log n).'],
['heap','Which statement is true for a max heap?',['left < node < right','parent ≥ children','all leaves contain max','siblings are sorted'],1,'Heap property compares parent with children only. Left and right siblings have no ordering guarantee.'],
['heap','Heap dequeue removes the root, then…',['deletes whole tree','moves last node to root and sinks it','sorts all nodes','moves left child to root always'],1,'Move the last node to the root and restore heap order by sinking it.'],
['heap','Heapsort is…',['O(n²)','O(n log n)','O(log n)','O(1)'],1,'Build a heap, repeatedly move the maximum to its final position and restore the heap.'],
['expr','Pre-order traversal of an expression tree produces…',['infix','Polish/prefix','Reverse Polish/postfix','breadth notation'],1,'VLR places the operator before its operands: prefix/Polish notation.'],
['expr','Post-order traversal of an expression tree produces…',['prefix','infix','postfix/Reverse Polish','B-tree order'],2,'LRV places the operator after operands: postfix/Reverse Polish notation.'],
['btree','A multiway node with k keys has how many pointers?',['k−1','k','k+1','2k'],2,'Course rule: k keys separate k+1 child ranges.'],
['btree','A B-tree of order 5 can hold at most how many keys per node?',['3','4','5','6'],1,'Order m means at most m pointers and m−1 keys. Order 5 → 4 keys.'],
['btree','When a full B-tree node splits, what happens to the median?',['deleted','stays in left node','moves up to parent','moves to rightmost leaf'],2,'The median is promoted to the parent; lower keys form one node and higher keys the other.'],
['btree','When can a B-tree gain height?',['any leaf insertion','only when the root splits','every split','when a leaf is half full'],1,'All non-root splits are absorbed upward. Only a root split creates a new level.'],
['btree','Minimum fullness: B*, compared with ordinary B-tree?',['1/2','2/3','3/4','100%'],1,'Course rule: B ≥ 1/2, B* ≥ 2/3, B** ≥ 3/4.'],
['btree','What is the key giveaway of a B+Tree?',['all data only in root','all data in leaves; index keys may repeat','every node has 2 children','no leaves'],1,'B+ internal nodes act as indexes; actual data is in linked leaves and index values can reappear there.'],
['btree','Why use a Prefix B+Tree?',['to store longer keys','to shrink index keys so nodes have higher fan-out','to remove leaves','to make a binary tree'],1,'Shorter separators fit more keys/pointers in each node, reducing tree height and disk seeks.'],
['btree','A Bit Tree stores mainly…',['whole objects in every index','the first distinction bit position','only leaf counts','AVL balance factors'],1,'The distinction bit is the first bit position where values differ; that can be enough to steer the search.'],
['trie','How does a trie choose branches?',['by comparing full key to a node value','using one part of the key at a time','by heap priority','by AVL balance factor'],1,'Each character or bit of the key selects the next branch; the path spells the key.']
];

var page=document.createElement('section');page.className='page';page.id='page-trees';
page.innerHTML=`<div class="tm-hero"><div class="tm-kicker">Week 4 + Week 6 · Tree Mastery</div><h1>Master every tree in the course</h1><p class="sub">Learn the rule, see the structure, practice the operation, then prove you can do it without looking.</p></div>
<div class="tm-tabs"><button class="tm-tab on" data-tmpane="learn">LEARN</button><button class="tm-tab" data-tmpane="lab">VISUAL LAB</button><button class="tm-tab" data-tmpane="questions">QUESTIONS</button><button class="tm-tab" data-tmpane="mastery">MASTERY</button></div>
<div class="tm-pane on" id="tm-pane-learn"><div class="tm-topics" id="tmTopics"></div><div id="tmLearn"></div></div>
<div class="tm-pane" id="tm-pane-lab">
<div class="tm-card"><span class="tm-badge">BST BUILDER + TRAVERSAL LAB</span><h3>Build a BST from any insertion sequence</h3><p class="tm-small">Type unique integers separated by spaces or commas. The tree is built using the course rule: smaller left, larger right.</p><div class="tm-inputrow"><input class="tm-input" id="tmSeq" value="5,3,8,2,4,6,9,1,7"><button class="tm-btn primary" id="tmBuild">BUILD TREE</button><button class="tm-btn" id="tmRandom">RANDOM</button></div></div>
<div class="tm-labgrid"><div><div class="tm-card"><h3>Search a value</h3><div class="tm-inputrow"><input class="tm-input" id="tmSearch" placeholder="value"><button class="tm-btn" id="tmSearchBtn">SEARCH PATH</button></div><div class="tm-result" id="tmSearchRes"></div></div><div class="tm-card"><h3>Traversal output</h3><div class="tm-outs"><div class="tm-out"><b>Pre-order · VLR</b><code id="tmPre"></code></div><div class="tm-out"><b>In-order · LVR</b><code id="tmIn"></code></div><div class="tm-out"><b>Post-order · LRV</b><code id="tmPost"></code></div><div class="tm-out"><b>Breadth-first</b><code id="tmBfs"></code></div></div></div></div><div><div id="tmTreeCanvas"></div></div></div>
<div class="tm-grid" style="margin-top:12px"><div class="tm-card"><span class="tm-badge">AVL ROTATION TRAINER</span><h3 id="tmRotQ"></h3><p class="tm-small" id="tmRotHint"></p><div class="tm-rot"><button data-rot="LL">LL</button><button data-rot="RR">RR</button><button data-rot="LR">LR</button><button data-rot="RL">RL</button></div><div class="tm-result" id="tmRotRes"></div><button class="tm-btn" id="tmRotNext" style="margin-top:8px">NEW CASE</button></div><div class="tm-card"><span class="tm-badge">B-TREE QUICK TRAINER</span><h3>Order → capacity</h3><p class="tm-small">Enter B-tree order m.</p><div class="tm-inputrow"><input class="tm-input" id="tmOrder" type="number" value="5" min="3" max="50"><button class="tm-btn" id="tmOrderBtn">CHECK</button></div><div class="tm-outs" id="tmOrderOut"></div></div></div>
</div>
<div class="tm-pane" id="tm-pane-questions"><div class="tm-topics" id="tmQTopics"></div><div id="tmQuestion"></div></div>
<div class="tm-pane" id="tm-pane-mastery"><div class="tm-card"><span class="tm-badge">SELF-CHECK</span><h3>Your tree mastery</h3><p class="tm-small">Tick a skill only when you can do it without opening the notes. Progress is saved in this browser.</p><div class="tm-scoreline" id="tmScore"></div><div class="tm-progress"><i id="tmBar"></i></div></div><div class="tm-check" id="tmSkills"></div></div>`;
wrap.appendChild(page);

function setPane(id){document.querySelectorAll('.tm-tab').forEach(b=>b.classList.toggle('on',b.dataset.tmpane===id));document.querySelectorAll('.tm-pane').forEach(p=>p.classList.toggle('on',p.id==='tm-pane-'+id));}
document.querySelectorAll('.tm-tab').forEach(b=>b.addEventListener('click',()=>setPane(b.dataset.tmpane)));

var topicKeys=Object.keys(topics), activeTopic='basics';
function buildTopicButtons(){var h='';topicKeys.forEach(k=>h+='<button class="tm-topic '+(k===activeTopic?'on':'')+'" data-topic="'+k+'">'+topics[k].name+'</button>');document.getElementById('tmTopics').innerHTML=h;document.querySelectorAll('#tmTopics .tm-topic').forEach(b=>b.onclick=function(){activeTopic=this.dataset.topic;buildTopicButtons();renderLearn();});}
function renderLearn(){var t=topics[activeTopic];document.getElementById('tmLearn').innerHTML='<div class="tm-card"><span class="tm-badge">'+t.week+' · WHAT YOU MUST MASTER</span><h3>'+t.name+'</h3><p>'+t.exam+'</p></div>'+t.html;}
buildTopicButtons();renderLearn();

function Node(v){this.v=v;this.l=null;this.r=null;}
function insert(root,v){if(!root)return new Node(v);if(v<root.v)root.l=insert(root.l,v);else if(v>root.v)root.r=insert(root.r,v);return root;}
function parseSeq(){var a=document.getElementById('tmSeq').value.split(/[\s,]+/).filter(Boolean).map(Number).filter(Number.isFinite),seen={};return a.filter(v=>!seen[v]&&(seen[v]=1));}
function traversals(root){var pre=[],ino=[],post=[],bfs=[];function p(n){if(!n)return;pre.push(n.v);p(n.l);p(n.r)}function i(n){if(!n)return;i(n.l);ino.push(n.v);i(n.r)}function o(n){if(!n)return;o(n.l);o(n.r);post.push(n.v)}p(root);i(root);o(root);if(root){var q=[root];while(q.length){var n=q.shift();bfs.push(n.v);if(n.l)q.push(n.l);if(n.r)q.push(n.r);}}return{pre:pre,ino:ino,post:post,bfs:bfs};}
function layout(root){var pts=[],x=0;function walk(n,d){if(!n)return;walk(n.l,d+1);n._x=45+x*54;n._y=38+d*66;x++;pts.push(n);walk(n.r,d+1);}walk(root,0);return pts;}
var currentRoot=null,currentPath=[];
function draw(){var box=document.getElementById('tmTreeCanvas');if(!currentRoot){box.innerHTML='<span class="tm-small">Build a tree first.</span>';return;}var pts=layout(currentRoot),w=Math.max(340,(pts.length+1)*54),h=Math.max(260,Math.max.apply(null,pts.map(n=>n._y))+50),lines='',nodes='';pts.forEach(n=>{if(n.l)lines+='<line x1="'+n._x+'" y1="'+n._y+'" x2="'+n.l._x+'" y2="'+n.l._y+'"/>';if(n.r)lines+='<line x1="'+n._x+'" y1="'+n._y+'" x2="'+n.r._x+'" y2="'+n.r._y+'"/>';});pts.forEach(n=>{var hi=currentPath.indexOf(n)>=0?' class="tm-path"':'';nodes+='<g'+hi+'><circle cx="'+n._x+'" cy="'+n._y+'" r="18"/><text x="'+n._x+'" y="'+n._y+'">'+n.v+'</text></g>';});box.innerHTML='<svg class="tm-svg" width="'+w+'" height="'+h+'" viewBox="0 0 '+w+' '+h+'">'+lines+nodes+'</svg>';}
function build(){var vals=parseSeq();currentRoot=null;vals.forEach(v=>currentRoot=insert(currentRoot,v));currentPath=[];var t=traversals(currentRoot);document.getElementById('tmPre').textContent=t.pre.join(', ');document.getElementById('tmIn').textContent=t.ino.join(', ');document.getElementById('tmPost').textContent=t.post.join(', ');document.getElementById('tmBfs').textContent=t.bfs.join(', ');document.getElementById('tmSearchRes').textContent='';draw();}
document.getElementById('tmBuild').onclick=build;document.getElementById('tmRandom').onclick=function(){var a=[],used={};while(a.length<9){var v=1+Math.floor(Math.random()*40);if(!used[v]){used[v]=1;a.push(v)}}document.getElementById('tmSeq').value=a.join(', ');build();};document.getElementById('tmSearchBtn').onclick=function(){var v=Number(document.getElementById('tmSearch').value);if(!Number.isFinite(v)||!currentRoot)return;var p=currentRoot,path=[];while(p){path.push(p);if(v===p.v)break;p=v<p.v?p.l:p.r;}currentPath=path;draw();var found=path.length&&path[path.length-1].v===v;document.getElementById('tmSearchRes').textContent=path.map(n=>n.v).join(' → ')+' → '+(found?'FOUND':'NULL · not present');document.getElementById('tmSearchRes').className='tm-result '+(found?'good':'bad');};
build();

var rotCases=[['30, 20, 10','LL','New key 10 lands left of 20, which is left of 30.'],['10, 20, 30','RR','New key 30 lands right of 20, which is right of 10.'],['30, 10, 20','LR','New key 20 lands right of left child 10.'],['10, 30, 20','RL','New key 20 lands left of right child 30.']];var rotNow=null;
function newRot(){rotNow=rotCases[Math.floor(Math.random()*rotCases.length)];document.getElementById('tmRotQ').textContent='Insert sequence: '+rotNow[0]+' · Which AVL case?';document.getElementById('tmRotHint').textContent='Classify from the lowest unbalanced node.';document.getElementById('tmRotRes').textContent='';document.getElementById('tmRotRes').className='tm-result';}
document.querySelectorAll('[data-rot]').forEach(b=>b.onclick=function(){var ok=this.dataset.rot===rotNow[1];document.getElementById('tmRotRes').textContent=(ok?'Correct. ':'Not quite. Correct = '+rotNow[1]+'. ')+rotNow[2]+' Fix: '+({LL:'single right rotation',RR:'single left rotation',LR:'left at child, then right at parent',RL:'right at child, then left at parent'}[rotNow[1]])+'.';document.getElementById('tmRotRes').className='tm-result '+(ok?'good':'bad');});document.getElementById('tmRotNext').onclick=newRot;newRot();
document.getElementById('tmOrderBtn').onclick=function(){var m=Math.max(3,Number(document.getElementById('tmOrder').value)||3),min=Math.ceil(m/2);document.getElementById('tmOrderOut').innerHTML='<div class="tm-out"><b>Max pointers</b><code>'+m+'</code></div><div class="tm-out"><b>Max keys</b><code>'+(m-1)+'</code></div><div class="tm-out"><b>Non-root minimum pointers k</b><code>ceil('+m+'/2) = '+min+'</code></div><div class="tm-out"><b>Non-root minimum keys</b><code>'+(min-1)+'</code></div><div class="tm-note"><b>Split trigger:</b> trying to hold '+m+' keys means overflow, because max is '+(m-1)+'.</div>';};document.getElementById('tmOrderBtn').click();

var qFilter='all',qList=[],qI=0,qHits=0;
function buildQTopics(){var ks=['all'].concat(topicKeys),h='';ks.forEach(k=>h+='<button class="tm-topic '+(k===qFilter?'on':'')+'" data-qtopic="'+k+'">'+(k==='all'?'ALL TREES':topics[k].name)+'</button>');document.getElementById('tmQTopics').innerHTML=h;document.querySelectorAll('#tmQTopics .tm-topic').forEach(b=>b.onclick=function(){qFilter=this.dataset.qtopic;startQ();});}
function startQ(){qList=QB.map((q,i)=>i).filter(i=>qFilter==='all'||QB[i][0]===qFilter);for(var i=qList.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1)),x=qList[i];qList[i]=qList[j];qList[j]=x;}qI=0;qHits=0;buildQTopics();renderQ();}
function renderQ(){if(!qList.length){document.getElementById('tmQuestion').innerHTML='<div class="tm-card">No questions for this filter.</div>';return;}if(qI>=qList.length){document.getElementById('tmQuestion').innerHTML='<div class="tm-qcard"><div class="tm-qmeta">RUN COMPLETE</div><div class="tm-qtext">'+qHits+' / '+qList.length+' correct</div><button class="tm-btn primary" id="tmRetry">RETRY</button></div>';document.getElementById('tmRetry').onclick=startQ;return;}var q=QB[qList[qI]],h='<div class="tm-qcard"><div class="tm-qmeta">'+topics[q[0]].name+' · '+(qI+1)+' / '+qList.length+' · SCORE '+qHits+'</div><div class="tm-qtext">'+q[1]+'</div>';q[2].forEach((o,i)=>h+='<button class="tm-opt" data-qi="'+i+'">'+String.fromCharCode(65+i)+'. '+o+'</button>');h+='<div class="tm-explain" id="tmExplain"></div><div class="tm-qnav"><button class="tm-btn" id="tmPrevQ">◀ PREVIOUS</button><button class="tm-btn primary" id="tmNextQ">NEXT ▶</button></div></div>';document.getElementById('tmQuestion').innerHTML=h;document.querySelectorAll('#tmQuestion .tm-opt').forEach(b=>b.onclick=function(){var pick=Number(this.dataset.qi),right=q[3];document.querySelectorAll('#tmQuestion .tm-opt').forEach((x,i)=>{x.disabled=true;if(i===right)x.classList.add('right');if(i===pick&&pick!==right)x.classList.add('wrong');});if(pick===right)qHits++;var ex=document.getElementById('tmExplain');ex.innerHTML='<b>'+(pick===right?'Correct.':'Correct answer: '+String.fromCharCode(65+right)+'.')+'</b> '+q[4];ex.classList.add('on');});document.getElementById('tmPrevQ').onclick=function(){qI=Math.max(0,qI-1);renderQ();};document.getElementById('tmNextQ').onclick=function(){qI++;renderQ();};}
startQ();

function loadSkills(){var data={};try{data=JSON.parse(localStorage.getItem('algoTreeMastery')||'{}')}catch(e){}var h='';skills.forEach((s,i)=>h+='<label class="tm-skill"><input type="checkbox" data-skill="'+i+'" '+(data[i]?'checked':'')+'><span><b>'+topics[s[0]].name+'</b><span>'+s[1]+'</span></span></label>');document.getElementById('tmSkills').innerHTML=h;document.querySelectorAll('[data-skill]').forEach(c=>c.onchange=saveSkills);updateSkillScore();}
function saveSkills(){var d={};document.querySelectorAll('[data-skill]').forEach(c=>d[c.dataset.skill]=c.checked);try{localStorage.setItem('algoTreeMastery',JSON.stringify(d))}catch(e){}updateSkillScore();}
function updateSkillScore(){var all=[].slice.call(document.querySelectorAll('[data-skill]')),n=all.filter(c=>c.checked).length,p=all.length?Math.round(n/all.length*100):0;document.getElementById('tmScore').textContent=n+' / '+all.length+' skills · '+p+'%';document.getElementById('tmBar').style.width=p+'%';}
loadSkills();
})();
